# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(stats)
    library(workflows)
}
b <- board_folder(path = "data")
v <- vetiver_pin_read(b, "cars_mpg", version = "20220605T213207Z-c2811")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
