name: update_data

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R 4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install dependencies
        run: |
          make install
      - name: Set up renv

        uses: r-lib/actions/setup-renv@v2

      - name: Run Data Extraction
        run: Rscript script/collect_data.R

      - name: Push data to Github
        run: |
          make save-file